# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python27:
      python.version: '2.7'
steps:
- task: JFrogPip@1
  inputs:
    artifactoryConnection: 'jfrogartifactory-v2'
    command: 'install'
    arguments: '-r requirements.txt'
    targetResolveRepo: 'hari-pypi'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'ls -al /home/vsts/.local/lib/python3.10/site-packages/*'
#- task: JFrogGenericArtifacts@1
#  inputs:
#     command: 'Upload'
#     connection: 'jfrogartifactory-v2'
#     specSource: 'taskConfiguration'
#     fileSpec: |
#       {
#         "files": [
#           {
#             "pattern": "/home/vsts/.local/lib/python3.10/*",
#             "target": "hari-pypi-local"
#           }
#         ]
#       }
#     failNoOp: true
- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'jfrogplatform-v2'
    command: 'jf rt u /home/vsts/.local/lib/python3.10/(*) hari-pypi-local/{1}/ --recursive=true'